README.md
README.zh-CN.md
src/BasicAbility/Masa.Contrib.BasicAbility.Dcc/Masa.Contrib.BasicAbility.Dcc.csproj
src/Data/Masa.Contrib.Data.Contracts.EF/Masa.Contrib.Data.Contracts.EF.csproj
src/Data/Masa.Contrib.Data.Contracts.EF/README.md
src/Data/Masa.Contrib.Data.Contracts.EF/README.zh-CN.md
src/Data/Masa.Contrib.Data.Contracts.EF/ServiceCollectionExtensions.cs
src/Data/Masa.Contrib.Data.UoW.EF/Masa.Contrib.Data.UoW.EF.csproj
src/Data/Masa.Contrib.Data.UoW.EF/README.md
src/Data/Masa.Contrib.Data.UoW.EF/README.zh-CN.md
src/Dispatcher/Masa.Contrib.Dispatcher.Events/DispatcherOptionsExtensions.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBusBuilder.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/Masa.Contrib.Dispatcher.Events.csproj
src/Dispatcher/Masa.Contrib.Dispatcher.Events/UseMiddlewareExtensions.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr.csproj
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF.csproj
src/Service/Masa.Contrib.Service.MinimalAPIs/Masa.Contrib.Service.MinimalAPIs.csproj
test/Masa.Contrib.Data.Contracts.EF.Tests/SoftDeleteTest.cs

* feat(EventBus): EventBus extension supports UseMiddleware
* refactor(Masa.Contrib.Data.Contracts.EF): Optimized use of UseSoftDelete method

feat(eventBus): EventBus extension supports UseMiddleware and Optimized use of UseSoftDelete method

---

src/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Dispatch/DispatcherBase.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/DispatcherExtensions.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/_Imports.cs
test/Masa.Contrib.Data.UoW.EF.Tests/TestUnitOfWork.cs
test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/BaseRepositoryTest.cs
test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/Masa.Contrib.Ddd.Domain.Repository.EF.Tests.csproj
test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/RepositoryTest.cs
test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/_Imports.cs
test/Masa.Contrib.Dispatcher.Events.Tests/EventHandlers/RegisterUserEventHandler.cs
test/Masa.Contrib.Dispatcher.Events.Tests/Events/RegisterUserEvent.cs
test/Masa.Contrib.Dispatcher.Events.Tests/FeaturesTest.cs
test/Masa.Contrib.Dispatcher.Events.Tests/SagaTest.cs
test/Masa.Contrib.Dispatcher.Events.Tests/_Imports.cs
test/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF.Tests/IntegrationEventLogServiceTest.cs

* EventBus: Throws an exception while retaining the original stack information and does not change the exception information (#25)
* Adapt to Utils.EntityFramework 0.4.0-preview.2 (#25)

fix(EventBus): Throws an exception while retaining the original stack information and does not change the exception information

---

src/Data/Masa.Contrib.Data.UoW.EF/DataConnectionStringProvider.cs
src/Data/Masa.Contrib.Data.UoW.EF/DbConnectionStringProvider.cs
src/Data/Masa.Contrib.Data.UoW.EF/DefaultConnectionStringProvider.cs
src/Data/Masa.Contrib.Data.UoW.EF/DispatcherOptionsExtensions.cs
src/Data/Masa.Contrib.Data.UoW.EF/README.md
src/Data/Masa.Contrib.Data.UoW.EF/README.zh-CN.md
src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWork.cs
src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWorkAccessor.cs
src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWorkManager.cs
src/Data/Masa.Contrib.Data.UoW.EF/_Imports.cs
src/Ddd/Masa.Contrib.Ddd.Domain.Repository.EF/Repository.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/DeleteLocalQueueExpiresProcessor.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/DeletePublishedExpireEventProcessor.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/InfiniteLoopProcessor.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/ProcessorBase.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/RetryByDataProcessor.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Processor/RetryByLocalQueueProcessor.cs
src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Servers/DefaultHostedService.cs
test/Masa.Contrib.Data.UoW.EF.Tests/CustomDbContext.cs
test/Masa.Contrib.Data.UoW.EF.Tests/Masa.Contrib.Data.UoW.EF.Tests.csproj
test/Masa.Contrib.Data.UoW.EF.Tests/TestUnitOfWork.cs
test/Masa.Contrib.Data.UoW.EF.Tests/_Imports.cs
test/Masa.Contrib.Data.UoW.EF.Tests/appsettings.json
test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/RepositoryTest.cs
test/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr.Tests/Internal/CustomizeProcessor.cs
test/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr.Tests/ProcessorTest.cs

* UoW: Adjust UoW documentation
* uoW: add IUnitOfWorkManager and IUnitOfWorkAccessor , Support for creating new DbContext, IUnitOfWork Add IServiceProvider 
* uoW: Extend UseUoW method for IEventBusBuilder
* IntegrationEvents.Dapr: Refactoring background tasks
* Adapt unit tests to new background tasks

feat(UoW): add IUnitOfWorkAccessor and IUnitOfWorkManager support CreateDbContextAsync

---

README.md
README.zh-CN.md
src/Authentication/Masa.Contrib.Authentication.Oidc.EntityFrameworkCore/ServiceCollectionExtensions.cs
src/BasicAbility/Masa.Contrib.BasicAbility.Auth/AuthClient.cs
src/BasicAbility/Masa.Contrib.BasicAbility.Auth/README.md
src/BasicAbility/Masa.Contrib.BasicAbility.Auth/README.zh-CN.md
src/BasicAbility/Masa.Contrib.BasicAbility.Auth/Service/TeamService.cs
src/BasicAbility/Masa.Contrib.BasicAbility.Auth/Service/UserService.cs
test/Masa.Contrib.BasicAbility.Auth.Tests/TeamServiceTest.cs
test/Masa.Contrib.BasicAbility.Auth.Tests/UserServiceTest.cs

auth sdk method modify and add auth readme

feat(auth sdk):update user center and add readme

---

src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.NormalGuid/NormalGuidGenerator.cs
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.NormalGuid/README.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.NormalGuid/README.zh-CN.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.SequentialGuid/README.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.SequentialGuid/README.zh-CN.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.SequentialGuid/SequentialGuidGenerator.cs
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake.Distributed.Redis/README.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake.Distributed.Redis/README.zh-CN.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake/BaseIdGenerator.cs
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake/MachineClockIdGenerator.cs
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake/README.md
src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake/README.zh-CN.md
test/Masa.Contrib.Data.IdGenerator.SequentialGuid.Tests/SequentialGuidGeneratorTest.cs
test/Masa.Contrib.Data.IdGenerator.Snowflake.BenchmarkDotnet.Tests/Benchmarks.cs
test/Masa.Contrib.Data.IdGenerator.Snowflake.BenchmarkDotnet.Tests/DistributedBenchmarks.cs
test/Masa.Contrib.Data.IdGenerator.Snowflake.BenchmarkDotnet.Tests/MachineClockBenchmarks.cs
test/Masa.Contrib.Data.IdGenerator.Snowflake.Tests/IdGeneratorTest.cs

IdGenerator: Create method changed to NewId

chore: Create method changed to NewId

---

src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWork.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBus.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/IInitializeServiceProvider.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/InitializeServiceProvider.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Middleware/TransactionMiddleware.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/README.md
src/Dispatcher/Masa.Contrib.Dispatcher.Events/README.zh-CN.md
src/Dispatcher/Masa.Contrib.Dispatcher.Events/ServiceCollectionExtensions.cs
src/Dispatcher/Masa.Contrib.Dispatcher.Events/Strategies/ExecutionStrategy.cs
test/Masa.Contrib.Ddd.Domain.Entities.Tests/Events/RegisterUserEvent.cs
test/Masa.Contrib.Ddd.Domain.Entities.Tests/User.cs
test/Masa.Contrib.Ddd.Domain.Integrated.Tests/DomainEventTest.cs
test/Masa.Contrib.Ddd.Domain.Integrated.Tests/Handlers/UserHandler.cs

1. Fixed that only the first data will be saved after calling EventBus.PublishAsync multiple times 
2. After repairing the data exception, if there are still transaction submissions in the future, the problem of data rollback error

fix(EventBus): Fix the issue that EventBus does not support multiple Publish

---

src/Utils/Masa.Utils.Exceptions/Extensions/ApplicationBuilderExtensions.cs
src/Utils/Masa.Utils.Exceptions/Handlers/ExceptionHandlerMiddleware.cs
src/Utils/Masa.Utils.Exceptions/Handlers/ExceptionHandlingMiddleware.cs
src/Utils/Masa.Utils.Exceptions/Handlers/GlobalExceptionFilter.cs
src/Utils/Masa.Utils.Exceptions/IMasaExceptionHandler.cs
src/Utils/Masa.Utils.Exceptions/MasaException.cs
src/Utils/Masa.Utils.Exceptions/Options/MasaExceptionHandlerOptions.cs
src/Utils/Masa.Utils.Exceptions/Options/MasaExceptionHandlingOptions.cs
src/Utils/Masa.Utils.Exceptions/UserFriendlyException.cs
src/Utils/Masa.Utils.Exceptions/_Imports.cs

Add ErrorCode to support multiple languages later

feat(Exception): Add ErrorCode to support multiple languages later

---

src/Contrib/Data/Contracts/Masa.Contrib.Data.Contracts.EFCore/DataFiltering/SoftDeleteSaveChangesFilter.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/CustomDbContext.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/DataFilterTest.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/EntityConfigurations/AddressEntityTypeConfiguration.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/EntityConfigurations/StudentEntityTypeConfiguration.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Masa.Contrib.Data.Contracts.EFCore.Tests.csproj
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Models/Address.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Models/Hobby.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Models/LogItem.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Models/Student.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/_Imports.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs

Fix association delete bug when there is a value object in the navigation property

fix(Contracts.EFCore): Fix association delete bug when there is a value object in the navigation property

---

src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/ServiceBaseTest.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/CustomServiceBase.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/UserService.cs

Refactoring the ParseMethod method

refactor(MinimalAPI): Refactoring the ParseMethod method

---

src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/CacheClientBase.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/DistributedCacheClientBase.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/ICacheClient.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IDistributedCacheClient.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IMultilevelCacheClient.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/MultilevelCacheClientBase.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/Options/CacheEntryOptions.cs

Supports nullable absolute expiration times

feat(Caching): Supports nullable absolute expiration times

---

src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/Extensions/ServiceCollectionExtensions.Core.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/TypeAlias/DefaultTypeAliasProvider.cs
src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/Extensions/DistributedCacheOptionsExtensions.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/appsettings.json
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/_Imports.cs
src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/MasaConfigurationExtensions.cs

Remove ITypeAliasProvider injection

fix: Remove ITypeAliasProvider injection

---

src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/DistributedCacheClientBase.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IDistributedCacheClient.cs
src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/RedisCacheClient.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs

pref: Delete the current memory cache immediately after the Remove method is executed
fix: Fix perform delete memory cache failure (when no cache is fetched)

pref(Caching): Delete the current memory cache immediately after the Remove method is executed

---

src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/RedisCacheClient.cs
src/Contrib/Caching/Distributed/Tests/Masa.Contrib.Caching.Distributed.StackExchangeRedis.Tests/DistributedCacheClientTest.cs
src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Internal/Extensions/DistributedCacheClientExtensions.cs
src/Contrib/Configuration/ConfigurationApi/Tests/Masa.Contrib.Configuration.ConfigurationApi.Dcc.Tests/DccTest.cs
src/Contrib/Data/Contracts/Masa.Contrib.Data.Contracts.EFCore/DataFiltering/SoftDeleteSaveChangesFilter.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/DataFilterTest.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/Models/Student.cs
src/Contrib/Data/Contracts/Tests/Masa.Contrib.Data.Contracts.EFCore.Tests/_Imports.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Filters/SaveChangeFilter.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Masa.Contrib.Data.EFCore.csproj
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
src/Utils/Extensions/Masa.Utils.Extensions.DotNet/TypeExtensions.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DotNet.Tests/TypeTest.cs

* Caching: Fix GetKeys failed to get information in IDistributedCacheClient
* ConfigurationApi: Fix failed to get config object
* Ddd: Optimize the problem that the creation time and update time cannot be updated due to the wrong user type

fix(softdelete): Fix GetKeys failed to get information in IDistributedCacheClient

---

src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/CallerOptionsExtensions.cs
src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/DefaultCallerProvider.cs
src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/ICallerProvider.cs
src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/Masa.Contrib.Service.Caller.DaprClient.csproj
src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/_Imports.cs
src/Contrib/Service/Caller/Tests/Masa.Contrib.Service.Caller.Tests/DefaultCallerProviderTest.cs
src/Contrib/Service/Caller/Tests/Masa.Contrib.Service.Caller.Tests/_Imports.cs
src/Contrib/Service/Caller/Tests/Scenes/Masa.Contrib.Service.Caller.AutomaticCaller.Tests/AutomaticCallerTest.cs
src/Contrib/Service/Caller/Tests/Scenes/Masa.Contrib.Service.Caller.AutomaticCaller.Tests/Callers/DaprCaller.cs
src/Utils/Extensions/Masa.Utils.Extensions.DotNet/StringExtensions.cs
src/Utils/Extensions/Masa.Utils.Extensions.DotNet/_Imports.cs

refactor: Refactor Caller.Dapr

refactor: Refactor Caller.Dapr

---

src/Utils/Extensions/Masa.Utils.Extensions.DependencyInjection/DefaultTypeProvider.cs
src/Utils/Extensions/Masa.Utils.Extensions.DependencyInjection/IScopedDependency.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/DependencyInjectionTest.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Domain/Repositories/IUserRepository.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Infrastructure/Repositories/RepositoryBase.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Infrastructure/Repositories/UserRepository.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Infrastructure/Services/CustomizeClientFactory.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Infrastructure/Services/EmptyClientFactory.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/Infrastructure/Services/NullCalculateProviderService.cs
src/Utils/Extensions/Tests/Masa.Utils.Extensions.DependencyInjection.Tests/_Imports.cs

refactor di

---

src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/MasaApp.cs
src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events/IEventBus.cs
src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/Options/CallerOptions.cs
src/Contrib/Caching/Distributed/Tests/Masa.Contrib.Caching.Distributed.StackExchangeRedis.Tests/DistributedCacheClientTest.cs
src/Contrib/Caching/Distributed/Tests/Masa.Contrib.Caching.Distributed.StackExchangeRedis.Tests/StackExchangeRedisCacheTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheTest.cs
src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/MasaConfigurationBuilderExtensions.cs
src/Contrib/Configuration/Masa.Contrib.Configuration/Options/ConfigurationOptions.cs
src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/ConfigurationTest.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/DomainEventBus.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/DomainService.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/Options/DispatcherOptions.cs
src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainEventBusTest.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventLogService.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventOptionsExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/IntegrationEventBus.cs
src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore.Tests/IntegrationEventLogContextTest.cs
src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore.Tests/IntegrationEventLogServiceTest.cs
src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore.Tests/_Imports.cs
src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.Tests/IntegrationEventBusTest.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/AssemblyResolutionTests.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceGlobalRouteOptions.cs

Modify and set the global Assembly collection and Remove GetAllEventTypes method

pref: Modify and set the global Assembly collection and Remove GetAllEventTypes method

---

src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/CacheEntry.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/CombinedCacheEntry.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/DistributedCacheClientBase.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IDistributedCacheClient.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IMultilevelCacheClient.cs
src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/MultilevelCacheClientBase.cs
src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/RedisCacheClient.cs
src/Contrib/Caching/Distributed/Tests/Masa.Contrib.Caching.Distributed.StackExchangeRedis.Tests/DistributedCacheClientTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs

refactor: Cache value allows null

---

src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.Cache.Storage/ServiceCollectionExtensions.cs
src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.Cache/ServiceCollectionExtensions.cs
src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/Caches/SyncCache.cs
src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/OpenIdConnectEFCore.cs
src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/Repositories/ClientRepository.cs
src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/_Imports.cs

Feature(oidc): optimize OIDC

---

src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/EventBusBuilderTest.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/EventHandlers/MiddlewareEventHandler.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Events/MiddlewareEvent.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Middleware/Custom2Middleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Middleware/CustomMiddleware.cs

middleware changed to first in first out

refactor(EventBus): middleware changed to first in first out

---

src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events/EventMiddleware.cs
src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events/IEventMiddleware.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events.FluentValidation/Middleware/ValidatorEventMiddleware.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBus.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBusBuilder.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Middleware/TransactionEventMiddleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests.Perfs/Extensions/Middleware/LoggingMiddleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/AssemblyResolutionTests.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/EventBusBuilderTest.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Middleware/Custom2EventMiddleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Middleware/CustomEventMiddleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Middleware/LoggingEventMiddleware.cs
src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/TestBase.cs
src/Contrib/Isolation/Masa.Contrib.Isolation/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Isolation/Masa.Contrib.Isolation/Middleware/IsolationEventMiddleware.cs
test/Masa.Framework.IntegrationTests.EventBus/Infrastructure/Middleware/RecordEventMiddleware.cs
test/Masa.Framework.IntegrationTests.EventBus/Infrastructure/Middleware/ValidatorEventMiddleware.cs
test/Masa.Framework.IntegrationTests.EventBus/TestBase.cs
test/Masa.Framework.IntegrationTests.EventBus/TestDispatcher.cs

I change 'IMiddleware' to 'IEventMiddleware'. and changed all inhert from IMiddleware subclass's name and base class name.

update: change IMiddleware to IEventMiddleware

---

src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Tests/DbContextTest.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Tests/DefaultConnectionStringProviderTest.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/DbConnectionStringProvider.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/DefaultConnectionStringProvider.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/DefaultConnectionStringProvider.cs
src/Contrib/Isolation/Masa.Contrib.Isolation/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Isolation/Masa.Contrib.Isolation/IsolationDbContextProvider.cs

Fixed that when the configuration is changed, the data context of the current request is not affected

fix(EFCore): Fixed that when the configuration is changed, the data context of the current request is not affected

---

src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/WebApplicationExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Internal/GlobalMinimalApiOptions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Internal/TypeHelper.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/MinimalAPITest.cs

feat(MinimalAPIs): Support AddMasaMinimalAPIs

---

src/BuildingBlocks/RulesEngine/Masa.BuildingBlocks.RulesEngine/Options/RulesEngineOptions.cs
src/BuildingBlocks/RulesEngine/Masa.BuildingBlocks.RulesEngine/ServiceCollectionExtensions.cs
src/Contrib/RulesEngine/Masa.Contrib.RulesEngine.MicrosoftRulesEngine/RulesEngineOptionsExtensions.cs

Unified rule engine registration method

refactor(RulesEngine): Unified rule engine registration method

---

src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/FluentValidationExtensions.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/Internal/RegularHelper.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/Validators/IdCardValidator.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/Validators/MasaAbstractValidator.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/Validators/PasswordValidator.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/Validators/PhoneValidator.cs
src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/_Imports.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/ChineseLetterNumberUnderlineValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/ChineseLetterNumberValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/ChineseLetterUnderlineValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/ChineseLetterValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/ChineseValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/EmailValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/Events/RegisterPortEvent.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/Events/RegisterUserEvent.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/IdCardOptionalValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/IdCardValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/IdentityValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/LetterNumberValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/LetterValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/LowerLetterValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/NumberValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/PasswordValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/PhoneOptionalValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/PhoneValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/PortValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/RequiredValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/UpperLetterValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/UrlValidatorTest.cs
src/Utils/Extensions/Validations/Tests/Masa.Utils.Extensions.Validations.FluentValidation.Tests/_Imports.cs

1. 添加`MasaAbstractValidator<T>` 抽象类，封装官方的When，提供WhenNotEmpty方法
2.  `IdCardValidator` 和 `PhoneValidator` 不再校验NULL值
3. 对应调整单元测试
4. 修改`PasswordValidator` 基类为 `MasaRegularExpressionValidator`
- `IdCardValidator` and `PhoneValidator` 在传入的值是Null的时候，将会通过校验，保持与官方内置验证器的一致逻辑
- 修改 `Masa.Utils.Extensions.Validations.FluentValidation.RegularHelper` 正则表达式 ,取消忽略空字符串的正则。
close #479 

feat:  Utils:  FluentValidation   校验忽略Null值，并且提供WhenNotEmpty方法

---

Masa.Framework.sln
src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/IDomainEventBus.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/DomainEventBus.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/IntegrationEventBus.cs
src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.Tests/IntegrationEventBusTest.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/EventBus.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/ILocalEventBus.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/LocalEventBus.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/_Imports.cs
src/Contrib/Dispatcher/Tests/Scenes/Masa.Contrib.Dispatcher.Events.Tests.Scenes.IntegrationEvent/EventBusTest.cs
src/Contrib/Dispatcher/Tests/Scenes/Masa.Contrib.Dispatcher.Events.Tests.Scenes.IntegrationEvent/Masa.Contrib.Dispatcher.Events.Tests.Scenes.IntegrationEvent.csproj
src/Contrib/Dispatcher/Tests/Scenes/Masa.Contrib.Dispatcher.Events.Tests.Scenes.IntegrationEvent/RegisterUserIntegrationEvent.cs
src/Contrib/Dispatcher/Tests/Scenes/Masa.Contrib.Dispatcher.Events.Tests.Scenes.IntegrationEvent/_Imports.cs

* Enqueue -> EnqueueAsync
* IEventBus supports publishing integration events

rename: Enqueue -> EnqueueAsync

---

src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/DefaultMasaDbContext.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Data/Orm/EFCore/Scenes/Masa.Contrib.Data.EFCore.Tests.Scenes.Isolation/CustomDbContext.cs
src/Contrib/Data/Orm/EFCore/Scenes/Masa.Contrib.Data.EFCore.Tests.Scenes.Isolation/MasaDbContextTest.cs

fix [issues-542](https://github.com/masastack/MASA.Framework/issues/542)

fix: fix issues-542

---

src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Extensions/StreamExtensions.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/ActivityExtensions.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/AspNetCoreInstrumentationHandler.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/Handler/HttpClientInstrumentHandler.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/MasaServiceExtensions.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/Tracing/OpenTelemetryInstrumentationOptions.cs
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc/_Imports.cs
src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Tsc.Test/Extensions/SteamTests.cs
src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Tsc.Test/Trace/ActivityTest.cs
src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Tsc.Test/Trace/TraceTests.cs

- Read the body stream instead of synchronization.
- if body size is less or equal 200k, tracing will record body ,else record in log with base64 encoding.

fix(tsc): fix record body bug in tracing

---

src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Internal/Isolation/DefaultIsolationConnectionStringProvider.cs
src/Contrib/Data/Orm/EFCore/Scenes/Masa.Contrib.Data.EFCore.Tests.Scenes.Isolation/DefaultIsolationConnectionStringProviderTest.cs

Fix ConnectionStrings options mode support (used in isolation scenarios)

fix: Fix ConnectionStrings options mode support

---

src/Contrib/Data/IdGenerator/Snowflake/Tests/Masa.Contrib.Data.IdGenerator.Snowflake.Distributed.Redis.Tests/IdGeneratorTest.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Helpers/ServiceBaseHelper.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceGlobalRouteOptions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceRouteOptions.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/ServiceBaseTest.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/OrderService.cs

Support public properties in MinimalAPIs
[issues-551](https://github.com/masastack/MASA.Framework/issues/551)

feat：Support public properties in MinimalAPIs

---

src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/WebApplicationExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Internal/GlobalMinimalApiOptions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/_Imports.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/MinimalAPITest.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/ServiceBaseTest.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/CustomServiceBase.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/GoodsService.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/OrderService.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/PersonService.cs
src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/_Imports.cs

[issues-561](https://github.com/masastack/MASA.Framework/issues/561)

fix: Fix After disabling automatic mapping, the mapping route is incomplete

---

src/Contrib/Extensions/Masa.Contrib.Extensions.BackgroundJobs/BackgroundJobOptions.cs
src/Contrib/Extensions/Tests/Masa.Contrib.Extensions.BackgroundJobs.Tests/BackgroundJobOptionsTest.cs

The default value described in the comment for the `MaxRetryTimes` is 10, but the `_maxRetryTimes` is set 30 default, I think 10 is a properly value, so I correct the `MaxRetryTimes` default value to 10
```c#
public class BackgroundJobOptions
{
private int _maxRetryTimes = 10;
}
```

fix: Correct the MaxRetryTimes default value to 10

---

src/Contrib/Data/IdGenerator/Snowflake/Masa.Contrib.Data.IdGenerator.Snowflake/BaseIdGenerator.cs

Twepoch 也应该根据TimestampType转换成对应精度的时间戳

fix:Twepoch timestamp at different accuracies

---

src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/MasaApp.cs
src/Contrib/Data/Contracts/Masa.Contrib.Data.Contracts/MasaDbContextBuilderExtensions.cs

1. UseFilter命名空间修改，Masa.Contrib.Data.Contracts项目与EF无关。
2. MasaApp增加TryAddAssemblies方法，应对已设置并需要增加的情况。

feat: UseFilter命名空间修改，MasaApp增加TryAddAssemblies

---

Directory.Build.props
src/BuildingBlocks/Isolation/Masa.BuildingBlocks.Isolation/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/MasaConfigurationExtensions.cs
src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Data/IdGenerator/NormalGuid/Masa.Contrib.Data.IdGenerator.NormalGuid/Extensions/IdGeneratorOptionsExtensions.cs
src/Contrib/Data/IdGenerator/SequentialGuid/Masa.Contrib.Data.IdGenerator.SequentialGuid/Extensions/IdGeneratorOptionsExtensions.cs
src/Contrib/Data/IdGenerator/Snowflake/Masa.Contrib.Data.IdGenerator.Snowflake/Extensions/IdGeneratorOptionsExtensions.cs
src/Contrib/Data/Mapping/Masa.Contrib.Data.Mapping.Mapster/ServiceCollectionExtensions.cs
src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain.Repository.EFCore/DispatcherOptionsExtensions.cs
src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/ServiceCollectionExtensions.cs
src/Contrib/Development/Masa.Contrib.Development.DaprStarter.AspNetCore/ServiceCollectionExtensions.cs
src/Contrib/Development/Masa.Contrib.Development.DaprStarter/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventOptionsExtensions.cs
src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Isolation/Masa.Contrib.Isolation.MultiEnvironment/IsolationBuilderExtensions.cs
src/Contrib/Isolation/Masa.Contrib.Isolation.MultiTenant/IsolationBuilderExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Extensions/ServiceCollectionExtensions.cs
src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Masa.Contrib.Service.MinimalAPIs.csproj
src/Contrib/StackSdks/Masa.Contrib.StackSdks.Scheduler/ServiceCollectionExtensions.cs

Fixed #703 : error when using the new .NET 8 Keyed Services

fix:Compatible with net8.0 IsKeyedService

---

src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.BlazorWebAssembly/BlazorCurrentPrincipalAccessor.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.BlazorWebAssembly/ComponentsClientScopeServiceProviderAccessor.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.BlazorWebAssembly/MasaComponentsClaimsCache.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.BlazorWebAssembly/ServiceCollectionExtensions.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.BlazorWebAssembly/_Imports.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.Core/IClientScopeServiceProviderAccessor.cs
src/Contrib/Authentication/Identity/Masa.Contrib.Authentication.Identity.Core/ICurrentPrincipalAccessor.cs
src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.BlazorWebAssembly.Tests/IdentityTest.cs

在 WebAssembly (WASM) 的环境中，由于它是单线程的，无法直接使用同步等待

🐛 fix: Fix BlazorCurrentPrincipalAccessor in BlazorWebAssembly

---

src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/Caches/SyncCache.cs

Replaced the `ClientQueryAsync` method with `ClientQuery().ToListAsync()` in the `ResetAsync` implementation. The `ClientQueryAsync` method and its internal logic have been removed, streamlining the asynchronous query process and improving code readability and maintainability.

refactor(SyncCache): simplify ResetAsync method
