- src/Ddd/Masa.Contrib.Ddd.Domain/README.md
- src/Ddd/Masa.Contrib.Ddd.Domain/README.zh-CN.md
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/Options/DispatcherOptions.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/README.md
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/README.zh-CN.md
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/UseMiddlewareExtensions.cs
* feat(EventBus): DispatcherOptions adds UseMiddleware support
* docs(EventBus): Modify EventBus usage documentation
> feat(eventBus): DispatcherOptions adds UseMiddleware support

- src/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Dispatch/DispatcherBase.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/Strategies/ExecutionStrategy.cs
* Dispatcher: Adjust the exception handling information to make the prompt information more friendly and easy to debug (#23)
> chore(Dispatcher): Adjust exception handling information

- test/Masa.Contrib.Dispatcher.Events.Tests/FeaturesTest.cs
* Adjust TestEventBusExceptionAsync methods (#26 )
> test(Dispatcher): Adjust TestEventBusExceptionAsync methods

- src/Ddd/Masa.Contrib.Ddd.Domain.Repository.EF/Internal/ServiceCollectionRepositoryExtensions.cs
- test/Masa.Contrib.Ddd.Domain.Repository.EF.Tests/BaseRepositoryTest.cs
Repository: Fix Entity to use IRepository, but we recommend using IRepository for aggregate root, not for Entity  (#33 )
> Fix Entity to use IRepository, but we recommend using IRepository for aggregate root, not IRepository for Entity

- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/BaseClient.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/DefaultCredentialProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/ICredentialProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/IOssClientFactory.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Options/AliyunStorageOptions.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.md
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.zh-CN.md
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/TestClient.cs
* Storage.Aliyun: Change the constructor to public
* Storage.Aliyun: Modify Storage document
* Storage.Aliyun: Support for configuration changes
> chore: Change the constructor to public

- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/DefaultStorageClient.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.md
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.zh-CN.md
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/ServiceCollectionExtensions.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/CustomizeClient.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/TestClient.cs
* Client renamed to DefaultStorageClient on Storage.Aliyun
* Repair Aliyun Storage document
> docs: Repair Aliyun Storage document

- README.md
- README.zh-CN.md
- src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.NormalGuid/README.md
- src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.SequentialGuid/README.md
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/BaseClient.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/DefaultCredentialProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/DefaultStorageClient.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/IAliyunStorageOptionProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/ICredentialProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Internal/DefaultAliyunStorageOptionProvider.cs
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.zh-CN.md
- src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/ServiceCollectionExtensions.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/BaseTest.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/CustomizeClient.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/CustomizeCredentialProvider.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/CustomizeNullClient.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/TestClient.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/TestCredentialProvider.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/TestStorage.cs
- test/Masa.Contrib.Storage.ObjectStorage.Aliyun.Tests/appsettings.json
* Home: Modify the homepage document
* IdGenerator: Modify the document
* Storage.Aliyun: Fix Chinese documentation errors
*  Storage.Aliyun: Fix upload error based on configuration file
> fix: Fix upload error based on configuration file

- src/Data/IdGenerator/Masa.Contrib.Data.IdGenerator.Snowflake/Internal/WorkerIdBackgroundServices.cs
Set the default value of WorkerId to false for background task initialization WorkerId
> chore: Set the default value of WorkerId to false for initializing WorkerId

- src/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBus.cs
Modify the prompt information address
> chore: Modify the prompt information address

- README.md
- README.zh-CN.md
- src/Data/Masa.Contrib.Data.EntityFrameworkCore/MasaDbContextOptions`.cs
* Fix: Fix errors using MySql
* Docs: Modify the homepage document
> Fix: Fix errors using MySql

- src/BasicAbility/Masa.Contrib.BasicAbility.Scheduler/Services/SchedulerJobService.cs
- test/Masa.Contrib.BasicAbility.Scheduler.Tests/SchedulerJobServiceTest.cs
> rename: rename AddbAsync to AddAsync

- Masa.Contrib.sln
- src/Identity/Masa.Contrib.Identity.IdentityModel/Const/ClaimType.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultIsolatedUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultMultiEnvironmentUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultMultiTenantUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/IdentityClaimOptions.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/ServiceCollectionExtensions.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/_Imports.cs
- test/Masa.Contrib.Identity.IdentityModel.Tests/TestIdentity.cs
UserContext add IdentityRole list
> feat:add user role

- src/BasicAbility/Masa.Contrib.BasicAbility.Auth/Service/UserService.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultIsolatedUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultMultiEnvironmentUserContext.cs
- src/Identity/Masa.Contrib.Identity.IdentityModel/DefaultMultiTenantUserContext.cs
- test/Masa.Contrib.Identity.IdentityModel.Tests/TestIdentity.cs
update userservice :UpdatePasswordAsync,UpdateBasicInfoAsync
> feat:update user service

- src/BasicAbility/Masa.Contrib.BasicAbility.Auth/Service/UserService.cs
- test/Masa.Contrib.BasicAbility.Auth.Tests/UserServiceTest.cs
add GetUserPortraitsAsync method
> feat(user service):add user portrait

- src/Ddd/Masa.Contrib.Ddd.Domain/README.md
- src/Ddd/Masa.Contrib.Ddd.Domain/README.zh-CN.md
> doc(IntegrationEvent): update documentation

- src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWork.cs
> fix(Dispatcher): fix transaction rollback

- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteClient.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/Options/AutoCompleteOptions.cs
- test/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
> chore: Default search is fuzzy

- src/Data/Masa.Contrib.Data.UoW.EF/UnitOfWork.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteClient.cs
- test/Masa.Contrib.Data.UoW.EF.Tests/TestUnitOfWork.cs
- test/Masa.Contrib.Dispatcher.Events.CheckMethodsType.Tests/Events/AddBasketEvent.cs
- test/Masa.Contrib.Dispatcher.Events.CheckMethodsType.Tests/_Imports.cs
- test/Masa.Contrib.Dispatcher.Events.Tests/CustomDbContext.cs
- test/Masa.Contrib.Dispatcher.Events.Tests/EventHandlers/CouponHandler.cs
- test/Masa.Contrib.Dispatcher.Events.Tests/Events/SendCouponEvent.cs
- test/Masa.Contrib.Dispatcher.Events.Tests/FeaturesTest.cs
- test/Masa.Contrib.Dispatcher.Events.Tests/Masa.Contrib.Dispatcher.Events.Tests.csproj
- test/Masa.Contrib.Dispatcher.Events.Tests/_Imports.cs
- test/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
Improve EventBus, AutoComplete unit testing
> test: Improve EventBus, AutoComplete unit testing

- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteClient.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteFactory.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/Options/AutoCompleteOptions.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/Options/AutoCompleteRelationsOptions.cs
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/ServiceCollectionExtensions.cs
- test/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
Fix search spaces and capitalization
> fix: Fix search spaces and capitalization

- test/Masa.Contrib.BasicAbility.Scheduler.Tests/SchedulerJobServiceTest.cs
> fix: UnitTest error

- Masa.Contrib.sln
- src/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBus.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Command/RegisterUserCommand.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Events/RegisterUserEvent.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Queries/CheckUserQuery.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Queries/CheckUserQueryValidator.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Queries/UserAgeQuery.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Queries/UserAgeQueryValidator.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/UserHandler.cs
- test/Masa.Contrib.Dispatcher.Tests/Domain/Aggregate/User.cs
- test/Masa.Contrib.Dispatcher.Tests/Infrastructure/CustomizeDbContext.cs
- test/Masa.Contrib.Dispatcher.Tests/Infrastructure/Extensions/DefaultPublisher.cs
- test/Masa.Contrib.Dispatcher.Tests/Infrastructure/Extensions/DispatcherOptionsExtensions.cs
- test/Masa.Contrib.Dispatcher.Tests/Infrastructure/Middleware/RecordMiddleware.cs
- test/Masa.Contrib.Dispatcher.Tests/Infrastructure/Middleware/ValidatorMiddleware.cs
- test/Masa.Contrib.Dispatcher.Tests/Masa.Contrib.Dispatcher.Tests.csproj
- test/Masa.Contrib.Dispatcher.Tests/TestBase.cs
- test/Masa.Contrib.Dispatcher.Tests/TestDispatcher.cs
- test/Masa.Contrib.Dispatcher.Tests/_Imports.cs
Fix non-transactional event middleware execution error
> fix(Dispatcher): Fix non-transactional event middleware execution error

- Directory.Build.props
Update Masa.Utils library version to 0.5.0-preview.6
> chore: Update Masa.Utils library version to 0.5.0-preview.6

- .github/workflows/pr_run_test_ci.yml
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/README.md
- src/SearchEngine/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/README.zh-CN.md
- test/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
> test(AutoComplete): Fix unit test errors

- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF/DispatcherOptionsExtensions.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/DispatcherOptionsExtensions.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/IntegrationEventBus.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/README.md
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/README.zh-CN.md
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/Servers/DefaultHostedService.cs
- src/Dispatcher/Masa.Contrib.Dispatcher.IntegrationEvents/ServiceCollectionExtensions.cs
- test/Masa.Contrib.Dispatcher.Tests/Application/Events/AddGoodsIntegrationEvent.cs
- test/Masa.Contrib.Dispatcher.Tests/TestDispatcher.cs
Support does not specify local message table service
> feat(IntegrationEventBus): Support does not specify local message table service

- Directory.Build.props
Update Masa.Utils library version to 0.5.0-rc.1
> chore: Update Masa.Utils library version to 0.5.0-rc.1

- Masa.Contrib.sln
- src/BasicAbility/Masa.Contrib.BasicAbility.Auth/Service/UserService.cs
- src/BasicAbility/Masa.Contrib.BasicAbility.Auth/_Imports.cs
- test/Masa.Contrib.BasicAbility.Auth.Tests/UserServiceTest.cs
- test/Masa.Contrib.BasicAbility.Auth.Tests/_Imports.cs
Reverts masastack/MASA.Contrib#155
> Revert "Feat/auth sdk user"

- src/Identity/Masa.Contrib.Identity.IdentityModel/README.md
- src/Identity/Masa.Contrib.Identity.IdentityModel/README.zh-CN.md
- src/Identity/Masa.Contrib.Identity.IdentityModel/ServiceCollectionExtensions.cs
> feat(Identity): Extend IdentityModel

- Directory.Build.props
Update Masa.Utils library version to 0.5.0
> chore: Update Masa.Utils library version to 0.5.0

- src/Utils/Masa.Utils.Exceptions/README.md
- src/Utils/Masa.Utils.Exceptions/README.zh-CN.md
Masa.Utils.Exceptions文档中IMasaExceptionHandler注入写法实测无效
> Masa.Utils.Exceptions文档修复

- .github/workflows/package_push_nuget.org.yml
> chore: Modify github CI

- src/BuildingBlocks/ReadWriteSpliting/Masa.BuildingBlocks.ReadWriteSpliting.Cqrs/Queries/Query.cs
Remove the restriction that Query results cannot be empty
> refactor(Cqrs): Remove the restriction that Query results cannot be empty

- src/BuildingBlocks/Authentication/Masa.BuildingBlocks.Authentication.Identity/UserContext.cs
Fix the problem that _currentUser is empty
> fix(Identity):  Fix the problem that _currentUser is empty

- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Entities/Entity.cs
Fix Entity error caused by merge
> fix(Ddd): Fix Entity error caused by merge

- src/BuildingBlocks/Authentication/Masa.BuildingBlocks.Authentication.Identity/UserContext.cs
- src/Contrib/SearchEngine/AutoComplete/Tests/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
> chore: Modify attribute access level

- src/Contrib/Configuration/Masa.Contrib.Configuration/MasaConfigurationProvider.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/ConfigurationTest.cs
Fix IConfiguration case sensitive issue
#201 
> fix(Configuration): Fix IConfiguration case sensitive issue

- src/Contrib/SearchEngine/AutoComplete/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteClient.cs
- src/Contrib/SearchEngine/AutoComplete/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/AutoCompleteFactory.cs
- src/Contrib/SearchEngine/AutoComplete/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/Options/AutoCompleteOptions.cs
- src/Contrib/SearchEngine/AutoComplete/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/Options/AutoCompleteRelationsOptions.cs
- src/Contrib/SearchEngine/AutoComplete/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch/ServiceCollectionExtensions.cs
- src/Contrib/SearchEngine/AutoComplete/Tests/Masa.Contrib.SearchEngine.AutoComplete.ElasticSearch.Tests/AutoCompleteTest.cs
- src/Utils/Data/Masa.Utils.Data.Elasticsearch/DefaultMasaElasticClient.cs
- src/Utils/Data/Masa.Utils.Data.Elasticsearch/Options/Document/Query/QueryBaseOptions.cs
Fix the problem of inserting complex text errors in the default configuration
> fix(AutoComplete): Fix the problem of inserting complex text errors in the default configuration

- README.md
> docs: Modify the Homepage Readme

- src/BuildingBlocks/Authentication/Masa.BuildingBlocks.Authentication.Identity/UserContext.cs
- src/Contrib/Authentication/Masa.Contrib.Authentication.Identity/ServiceCollectionExtensions.cs
- src/Contrib/Authentication/Tests/Masa.Contrib.Authentication.Identity.Tests/Masa.Contrib.Authentication.Identity.Tests.csproj
- src/Contrib/Authentication/Tests/Masa.Contrib.Authentication.Identity.Tests/TestIdentity.cs
- src/Contrib/Authentication/Tests/Masa.Contrib.Authentication.Identity.Tests/_Imports.cs
remove useless code & AddMasaIdentityModel extension supports name
> refactor(Identity): remove useless code & AddMasaIdentityModel extension supports name

- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/DefaultResponseMessage.cs
- src/Contrib/Service/Caller/Tests/Masa.Contrib.Service.Caller.Tests/DefaultXmlResponseMessage.cs
- src/Contrib/Service/Caller/Tests/Masa.Contrib.Service.Caller.Tests/HttpClientCallerTest.cs
- src/Contrib/Service/Caller/Tests/Masa.Contrib.Service.Caller.Tests/_Imports.cs
Fix Caller does not support response value as null
> fix(Caller): Fix Caller does not support response value as null

- src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/Options/CallerOptions.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/ServiceCollectionExtensions.cs
- src/Contrib/Service/Caller/Tests/Scenes/Masa.Contrib.Service.Caller.AutomaticCaller.Tests/CallerTest.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Scheduler/ServiceCollectionExtensions.cs
> feat(Caller): Add DisableAutoRegistration

- src/Contrib/Data/Mapping/Masa.Contrib.Data.Mapping.Mapster/DefaultMappingConfigProvider.cs
- src/Contrib/Data/Mapping/Tests/Masa.Contrib.Data.Mapping.Mapster.Tests/Dto/AddressItemDto.cs
- src/Contrib/Data/Mapping/Tests/Masa.Contrib.Data.Mapping.Mapster.Tests/Dto/OrderDto.cs
- src/Contrib/Data/Mapping/Tests/Masa.Contrib.Data.Mapping.Mapster.Tests/Dto/UserDto.cs
- src/Contrib/Data/Mapping/Tests/Masa.Contrib.Data.Mapping.Mapster.Tests/MappingTest.cs
- src/Contrib/Data/Mapping/Tests/Masa.Contrib.Data.Mapping.Mapster.Tests/Masa.Contrib.Data.Mapping.Mapster.Tests.csproj
> fix(Mapster): Fix Mapster nested type error problem

- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Helpers/ServiceBaseHelper.cs
- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs
- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceGlobalRouteOptions.cs
- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceRouteOptions.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/MinimalAPITest.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/RoutePatternTest.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/ServiceBaseTest.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/CatalogService.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/CustomServiceBase.cs
- src/Contrib/Service/Tests/Masa.Contrib.Service.MinimalAPIs.Tests/Services/UserService.cs
Add DefaultHttpMethods、DisableTrimStartMethodPrefix
> feat(MinimalAPI): Add DefaultHttpMethods、DisableTrimStartMethodPrefix

- src/Contrib/Configuration/ConfigurationApi/Tests/Masa.Contrib.Configuration.ConfigurationApi.Dcc.Tests/DccTest.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/WebApplicationBuilderExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Masa.Contrib.Configuration.csproj
- src/Contrib/Configuration/Masa.Contrib.Configuration/README.md
- src/Contrib/Configuration/Masa.Contrib.Configuration/README.zh-CN.md
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/ConfigurationTest.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/WebApplicationBuilderTest.cs
Add ServiceCollection extension AddMasaConfiguration
> refactor(Configuration): Add ServiceCollection extension AddMasaConfiguration

- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/DispatcherOptionsExtensions.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventLogEntityTypeConfiguration.cs
Support custom local message table mapping
> feat(IntegrationEventLog): Support custom local message table mapping

- src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/ConfigurationApiExtensions.cs
- src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/MasaConfigurationExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/MasaConfigurationBuilderExtensions.cs
- src/Contrib/Data/Contracts/Masa.Contrib.Data.Contracts.EFCore/MasaDbContextOptionsBuilderExtensions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/ServiceCollectionExtensions.cs
> fix: Modify namespace

- Masa.Framework.sln.DotSettings
add word 'Masa' into `DotSettings` file. fix warning for spell checking.
> chore: fix warning for spell checking

- Masa.Framework.sln
- src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/CallerBase.cs
- src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/IAuthenticationService.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/AuthenticationOptions.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/AuthenticationService.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Extensions/AuthenticationOptionsExtensions.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Extensions/CallerOptionsExtensions.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/ITokenValidatorHandler.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Jwt/ClientRefreshTokenOptions.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Jwt/JwtTokenValidatorHandler.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Jwt/JwtTokenValidatorOptions.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.csproj
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/README.md
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/README.zh-CN.md
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/TokenProvider.cs
- src/Contrib/Service/Caller/Authentication/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect/_Imports.cs
- src/Contrib/Service/Caller/Authentication/Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests/AuthenticationOptionsExtensionsTest.cs
- src/Contrib/Service/Caller/Authentication/Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests/AuthenticationServiceTest.cs
- src/Contrib/Service/Caller/Authentication/Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests/CallerOptionsExtensionsTest.cs
- src/Contrib/Service/Caller/Authentication/Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests.csproj
- src/Contrib/Service/Caller/Authentication/Tests/Masa.Contrib.Service.Caller.Authentication.OpenIdConnect.Tests/_Imports.cs
> feat(Caller): Support OpenIdConnect

- src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests.Perfs/Extensions/EventHandlers/CouponHandler.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr.AspNetCore/DaprBackgroundService.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr.AspNetCore/DefaultAppPortProvider.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr.AspNetCore/IAppPortProvider.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr.AspNetCore/ServiceCollectionExtensions.cs
- src/Utils/Security/Masa.Utils.Security.Cryptography/DesUtils.cs
fix bad code smell and dapr starter uses https first
> fix: fix bad code smell

- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr/DaprProcess.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr/DaprProvider.cs
- src/Utils/Development/Dapr/Masa.Utils.Development.Dapr/IDaprProvider.cs
Modify to stop the dapr process
> fix: Modify to stop the dapr process

- Directory.Build.props
Fix package source address error
> fix: Fix package source address error

- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/README.md
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/README.zh-CN.md
- src/Utils/Masa.Utils.Exceptions/Handlers/ExceptionHandlerMiddleware.cs
- src/Utils/Masa.Utils.Exceptions/Handlers/ExceptionHandlingMiddleware.cs
- src/Utils/Masa.Utils.Exceptions/Handlers/GlobalExceptionFilter.cs
- src/Utils/Masa.Utils.Exceptions/MasaExceptionContext.cs
fix(Exception): Services that support the Scoped lifecycle
feature(Exception): MasaExceptionContext Support IServiceProvider
> fix(exception): Services that support the Scoped lifecycle

- src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.md
- src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
> chore: Modify Document

- src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.Cache/ServiceCollectionExtensions.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/README.md
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/README.zh-CN.md
- src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/MasaConfigurationExtensions.cs
- src/Contrib/Configuration/ConfigurationApi/Tests/Masa.Contrib.Configuration.ConfigurationApi.Dcc.Tests/DccTest.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/ServiceCollectionExtensions.cs
Delete the overloaded part to optimize the user experience
> perf(Caching): Delete the overloaded part to optimize the user experience

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/Extensions/ServiceCollectionExtensions.cs
Adjust the default value of some overloaded methods to optimize the user experience
> pref(Caching): Adjust the default value of some overloaded methods to optimize the user experience

- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/ServiceCollectionExtensions.cs
> Feature(auth): sdk auth bind support  EnvironmentProvider with blazor

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Consts/CacheKeyConsts.cs
- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/SubjectPermissionRelationModel.cs
- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/UserModel.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/AuthClient.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/ThirdPartyIdpCacheService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/ServiceCollectionExtensions.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/_Imports.cs
> find user by id use cache

- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Filters/SaveChangeFilter.cs
Fix the problem of creator assignment failure  Source: https://github.com/masastack/MASA.Framework/pull/322
> fix(EFCore): Fix the problem of creator assignment failure

- src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/EventHandlerAttribute.cs
- src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Dispatch/SagaDispatcher.cs
- src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/EventHandlers/AddGoodsEventHandler.cs
- src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/Events/AddGoodsEvent.cs
- src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests/SagaTest.cs
Fixed EventBus not supporting IEventHandler
> fix: Fixed EventBus not supporting IEventHandler

- src/Contrib/Development/Masa.Contrib.Development.DaprStarter/DaprProcess.cs
Stop heartbeat detection when dapr stops
> feature: Stop heartbeat detection when dapr stops

- src/BuildingBlocks/Exception/Masa.BuildingBlocks.Exceptions.Tests/MasaArgumentExceptionTest.cs
- src/BuildingBlocks/Exception/Masa.BuildingBlocks.Exceptions/MasaArgumentException.cs
- src/BuildingBlocks/Exception/Masa.BuildingBlocks.Exceptions/MasaValidatorException.cs
The compiler no longer prompts for null reference errors
> chore: The compiler no longer prompts for null reference errors

- Masa.Framework.sln
- src/BuildingBlocks/Data/Masa.BuildingBlocks.Data.Contracts/Masa.BuildingBlocks.Data.Contracts.csproj
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/_Imports.cs
- src/BuildingBlocks/RulesEngine/Masa.BuildingBlocks.RulesEngine/_Imports.cs
- src/BuildingBlocks/StackSdks/Masa.BuildingBlocks.StackSdks.Tsc.Contracts/_Imports.cs
- src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.EFCore/_Imports.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Tests/_Imports.cs
- src/Contrib/RulesEngine/Tests/Masa.Contrib.RulesEngine.MicrosoftRulesEngine.Tests/_Imports.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc.Elasticsearch/_Imports.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Tsc.Elasticsearch.Tests/_Imports.cs
- src/Utils/Models/Masa.Utils.Models.Config/Masa.Utils.Models.Config.csproj
- src/Utils/Models/Masa.Utils.Models.Config/Paginated/PaginatedListBase.cs
- src/Utils/Models/Masa.Utils.Models.Config/Request/RequestPageBase.cs
- src/Utils/Models/Masa.Utils.Models.Config/Response/ResponseBase.cs
> feat: Add Model.Config

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
Fix GetList subscription event error
> fix(Caching): Fix GetList subscription event error

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> feature(userService):GetUserPortraitsAsync method return UserModels

- src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.BlazorServer.Tests/IdentityTest.cs
- src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.BlazorWebAssembly.Tests/IdentityTest.cs
- src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.Tests/CustomUser.cs
- src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.Tests/CustomUser2.cs
- src/Contrib/Authentication/Identity/Tests/Masa.Contrib.Authentication.Identity.Tests/IdentityTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/Infrastructure/CustomDistributedCacheClient.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Configuration/ConfigurationApi/Tests/Masa.Contrib.Configuration.ConfigurationApi.Dcc.Tests/DccTest.cs
- src/Contrib/Data/IdGenerator/Snowflake/Tests/Masa.Contrib.Data.IdGenerator.Snowflake.Distributed.Redis.Tests/IdGeneratorTest.cs
- src/Contrib/Data/IdGenerator/Snowflake/Tests/Masa.Contrib.Data.IdGenerator.Snowflake.Distributed.Redis.Tests/Infrastructure/CustomMachineClockIdGenerator.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain.Repository.EFCore/Internal/ServiceCollectionRepositoryExtensions.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Repository.EFCore.IntegrationTests/CustomDispatcherOptions.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Repository.EFCore.IntegrationTests/TestSoftDelete.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/README.md
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/README.zh-CN.md
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/README.md
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/README.zh-CN.md
> rename: Customer -> Custom

- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain.Tests/EventTest.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain.Tests/OrderPaymentFailedIntegrationDomainEvent.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain.Tests/OrderPaymentSucceededIntegrationDomainEvent.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain.Tests/_Imports.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/IntegrationDomainEvent.cs
Optimizing integration events must reload Topic
> pref: Optimizing integration events must reload Topic

- src/Contrib/Configuration/ConfigurationApi/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Masa.Contrib.Configuration.ConfigurationApi.Dcc.csproj
- src/Contrib/Configuration/Masa.Contrib.Configuration/DefaultMasaConfigurationSourceProvider.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/WebApplicationBuilderExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/IMasaConfigurationBuilder.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/IMasaConfigurationSourceProvider.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/ConfigurationTest.cs
Optimize the Configuration experience
> perf(Configuration): Optimize the Configuration experience

- src/BuildingBlocks/Data/Masa.BuildingBlocks.Data.UoW/IUnitOfWork.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/UnitOfWork.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain.Repository.EFCore/Repository.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Repository.EFCore.IntegrationTests/TestSoftDelete.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Repository.EFCore.Tests/RepositoryTest.cs
Delete is not a responsibility method of IUnitOfWork
> chore: Delete is not a responsibility method of IUnitOfWork

- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/WebApplicationBuilderExtensions.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/ConfigurationTest.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/Masa.Contrib.Configuration.Tests.csproj
- src/Contrib/Configuration/Tests/Scenes/Masa.Contrib.Configuration.Tests.Scenes.AutoMap/ConfigurationTest.cs
- src/Contrib/Configuration/Tests/Scenes/Masa.Contrib.Configuration.Tests.Scenes.AutoMap/Masa.Contrib.Configuration.Tests.Scenes.AutoMap.csproj
- src/Contrib/Configuration/Tests/Scenes/Masa.Contrib.Configuration.Tests.Scenes.AutoMap/_Imports.cs
- src/Contrib/Configuration/Tests/Scenes/Masa.Contrib.Configuration.Tests.Scenes.AutoMap/appsettings.json
- src/Contrib/Configuration/Tests/Scenes/Masa.Contrib.Configuration.Tests.Scenes.DisableAutoMap/ServiceCollectionExtensionsTest.cs
Fix automatic mapping failure due to wrong positioning method when only using MasaConfiguration
> fix(Configuration): Fix automatic mapping failure due to wrong positioning method when only using MasaConfiguration

- src/BuildingBlocks/Service/Masa.BuildingBlocks.Service.Caller/AbstractCaller.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.DaprClient/DaprCaller.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller.HttpClient/HttpClientCaller.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/DefaultResponseMessage.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/JsonRequestMessage.cs
- src/Contrib/Service/Caller/Masa.Contrib.Service.Caller/XmlRequestMessage.cs
Caller does not support synchronous calling asynchronous
> refactor: Caller does not support synchronous calling asynchronous

- src/Contrib/Development/Masa.Contrib.Development.DaprStarter/DaprProcessBase.cs
- src/Contrib/Development/Masa.Contrib.Development.DaprStarter/Process/ProcessProvider.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Publisher.cs
- src/Contrib/Dispatcher/Tests/Masa.Contrib.Dispatcher.Events.Tests.Perfs/Benchmarks.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Tsc.Elasticsearch/Extenistions/JsonElementExtensions.cs
- src/Utils/Extensions/Masa.Utils.Extensions.DotNet/EnglishPluralizationService.cs
- src/Utils/Security/Masa.Utils.Security.Cryptography/MD5Utils.cs
Fix integration event sending content error
> fix: Fix integration event sending content error

- src/BuildingBlocks/Data/Masa.BuildingBlocks.Data.UoW/IUnitOfWork.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Extensions/DispatcherOptionsExtensions.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Extensions/DomainEventOptionsExtensions.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Extensions/EventBusBuilderExtensions.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/Transaction.cs
- src/Contrib/Data/UoW/Masa.Contrib.Data.UoW.EFCore/UnitOfWork.cs
- src/Contrib/Data/UoW/Tests/Masa.Contrib.Data.UoW.EFCore.Tests/UnitOfWorkAccessorTest.cs
- src/Contrib/Data/UoW/Tests/Masa.Contrib.Data.UoW.EFCore.Tests/UnitOfWorkManagerTest.cs
- src/Contrib/Data/UoW/Tests/Masa.Contrib.Data.UoW.EFCore.Tests/UnitOfWorkTest.cs
- src/Contrib/Data/UoW/Tests/Masa.Contrib.Data.UoW.EFCore.Tests/_Imports.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain.Repository.EFCore/Repository.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Repository.EFCore.Tests/RepositoryTest.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/IntegrationEventBus.cs
- src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/EventBus.cs
- src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Internal/Middleware/TransactionMiddleware.cs
- src/Contrib/Dispatcher/Masa.Contrib.Dispatcher.Events/Options/DispatcherOptions.cs
Optimize the experience of only sending integration events
> pref: Optimize the experience of only sending integration events

- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Repositories/RepositoryBase.cs
GetPaginatedListAsync Supported override
> pref: GetPaginatedListAsync Supported override

- Masa.Framework.sln
- src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/ConnectionStringNameAttribute.cs
- src/BuildingBlocks/Data/Masa.BuildingBlocks.Data/Options/Internal/DbContextNameRelationOptions.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/ConnectionStringNameTest.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Infrastructure/CustomDbContext.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Infrastructure/CustomDbContextBase.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Infrastructure/CustomQuery2DbContext.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Infrastructure/CustomQuery3DbContext.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Infrastructure/CustomQueryDbContext.cs
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/Masa.BuildingBlocks.Data.Tests.csproj
- src/BuildingBlocks/Data/Tests/Masa.BuildingBlocks.Data.Tests/_Imports.cs
- src/Contrib/Isolation/UoW/Masa.Contrib.Isolation.UoW.EFCore/Extensions/DomainEventOptionsExtensions.cs
* Optimize multiple acquisitions of ConnectionStringName based on DbContextType
* MasaDbContextBuilder is not a required parameter
> pref(ConnectionStringName): Optimize multiple acquisitions of ConnectionStringName based on DbContextType

- Directory.Build.props
Copyright changed to MASA Stack
> chore: Copyright changed to MASA Stack

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
Fix occasional errors when deleting data through the cache
> pref(Caching): Fix occasional errors when deleting data through the cache

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature:register user add return userModel

- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Entities/AggregateRoot.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Entities/IGenerateDomainEvents.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Services/DomainService.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/ServiceCollectionExtensions.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainEventBusTest.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainServices/UserDomainService.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/_Imports.cs
Optimize the experience of using DomainService
> pref(DDD): Optimize the experience of using DomainService

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/VerifyMsgCodeModel.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature(auth sdk):update userService verfyMsgCode

- src/Utils/Extensions/Masa.Utils.Extensions.DotNet/CollectionExtensions.cs
> chore: modify method name

- src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.md
- src/Contrib/Caching/Distributed/Masa.Contrib.Caching.Distributed.StackExchangeRedis/README.zh-CN.md
- src/Contrib/Caching/Distributed/Tests/Masa.Contrib.Caching.Distributed.StackExchangeRedis.Tests/appsettings.json
> chore(redis): Delete useless configuration

- .github/ISSUE_TEMPLATE/01_bug_report.md
- .github/ISSUE_TEMPLATE/02_feature.md
- .github/ISSUE_TEMPLATE/03_blank.md
- .github/ISSUE_TEMPLATE/config.yml
> chore(framework): Add Issues Template

- codecov.yml
Ignore statistics MasaStack unit tests
> ci: Ignore statistics MasaStack unit tests

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/RemoveUserModel.cs
- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature:sdk auth userService add removeUser method

- src/BuildingBlocks/SearchEngine/Masa.BuildingBlocks.SearchEngine.AutoComplete/Extensions/ServiceCollectionExtensions.cs
> feat(AutoComplete): Add AutoComplete extension

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
use ```Masa.Contrib.Caching.Distributed.StackExchangeRedis``` and ```Masa.Contrib.Caching.MultilevelCache``` package. when local remove  a cache, server end not remove.
> fix(MultilevelCache):multilevel cache not update question,

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature(sdk auth):user service add FindListByAccountsAsync、GetUserSystemDataAsync

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature(Unified naming)：sdk auth server unified method name

- src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/CombinedCacheEntry.cs
- src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/IMultilevelCacheClient.cs
- src/BuildingBlocks/Caching/Masa.BuildingBlocks.Caching/MultilevelCacheClientBase.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/Internal/Options/SetOptions.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
Fix the validity period of GetOrSet memory cache
> fix(Caching): Fix the validity period of GetOrSet memory cache

- src/Contrib/Configuration/Masa.Contrib.Configuration/DefaultMasaConfigurationSourceProvider.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/IMasaConfigurationSourceProvider.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Internal/ConfigurationConstant.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/MasaConfigurationProvider.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/MasaConfigurationSource.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/MigrateConfigurationRelationsInfo.cs
- src/Contrib/Configuration/Masa.Contrib.Configuration/Options/ConfigurationOptions.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/WebApplicationBuilderTest.cs
- src/Contrib/Configuration/Tests/Masa.Contrib.Configuration.Tests/logging.json
Added configuration mapping support and added Logging mapping
> fix(Configuration): Support adding configuration mapping, default Logging -> LocalLogging

- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
> Fix(sdk auth):fix user service GetSystemDataAsync error

- .github/ISSUE_TEMPLATE/config.yml
> chore: Modify Issues template

- README.md
> chroe: fixed readme.md link error

- src/Utils/Extensions/Validations/Masa.Utils.Extensions.Validations.FluentValidation/FluentValidationExtensions.cs
fix: support nullable property
> fix: support nullable property

- src/Contrib/Authentication/OpenIdConnect/Tests/Masa.Contrib.Authentication.OpenIdConnect.EFCore.Tests/OidcDbContextOptionsTest.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Tests/DbContextTest.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContext.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextBuilder.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextOptions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextOptionsBuilder.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextOptionsBuilder`.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextOptions`.cs
> rename: Pularlizing -> Pluralizing

- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Attributes/IgnoreRouteAttribute.cs
- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/Attributes/RoutePatternAttribute .cs
> chore: Modify namespace

- src/Contrib/Storage/ObjectStorage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Options/AliyunStorageConfigureOptions.cs
Modify the access level of the method
> chore: Modify the access level of the method

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
> chore: Adjust cache validity period

- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/DomainCommand.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/DomainEvent.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/DomainQuery.cs
- src/BuildingBlocks/Ddd/Domain/Masa.BuildingBlocks.Ddd.Domain/Events/IntegrationDomainEvent.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events/Event.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.Events/_Imports.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.IntegrationEvents/IntegrationEvent.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.IntegrationEvents/Internal/IntegrationEventTopic.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.IntegrationEvents/Logs/IntegrationEventLog.cs
- src/BuildingBlocks/Dispatcher/Masa.BuildingBlocks.Dispatcher.IntegrationEvents/_Imports.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Publisher.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventLogService.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore/IntegrationEventOptionsExtensions.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/IPublisher.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Internal/IntegrationEventLogItem.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Processor/RetryByDataProcessor.cs
- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents/Processor/SendByDataProcessor.cs
- src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.EventLogs.EFCore.Tests/IntegrationEventLogServiceTest.cs
- src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.Tests/ProcessorTest.cs
- src/Contrib/Dispatcher/IntegrationEvents/Tests/Masa.Contrib.Dispatcher.IntegrationEvents.Tests/SendByDataProcessorTest.cs
- test/Masa.Framework.IntegrationTests.EventBus/Infrastructure/Extensions/DefaultPublisher.cs
[issues-557](https://github.com/masastack/MASA.Framework/issues/557)
> pref: issues 557

- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Tests/TestBase.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Extensions/ServiceCollectionExtensions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Filters/EmptySaveFilter.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Internal/Extensions/DbContextExtensions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/Internal/Extensions/DbContextOptionsExtensions.cs
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore/MasaDbContextOptions.cs
Optimize getting masa data context
> pref: Optimize getting masa data context

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
> rename: PubSub -> Pub

- src/BuildingBlocks/Extensions/Masa.BuildingBlocks.Extensions.BackgroundJobs/BackgroundJobBase.cs
New no-argument constructor BackgroundJobBase
> feat: New no-argument constructor BackgroundJobBase

- src/Contrib/Globalization/Masa.Contrib.Globalization.I18n.Dcc/DccI18nResourceContributor.cs
- src/Contrib/Globalization/Tests/Masa.Contrib.Globalization.I18n.Dcc.Tests/I18nTest.cs
> fix: Fix I18n.Dcc does not support multilingual configuration in nested format

- src/Utils/Extensions/Masa.Utils.Extensions.DotNet/Utils/AttributeUtils.cs
> chore: Modify Tips

- src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptions.cs
- src/BuildingBlocks/Development/Masa.BuildingBlocks.Development.DaprStarter/Options/DaprOptionsBase.cs
- src/Contrib/Development/Masa.Contrib.Development.DaprStarter/DaprProcessBase.cs
- src/Contrib/Development/Masa.Contrib.Development.DaprStarter/_Imports.cs
- src/Contrib/Development/Tests/Masa.Contrib.Development.DaprStarter.Tests/DaprProcessTest.cs
- src/Contrib/Development/Tests/Masa.Contrib.Development.DaprStarter.Tests/Internal/CustomDaprProcess.cs
- src/Contrib/Development/Tests/Masa.Contrib.Development.DaprStarter.Tests/_Imports.cs
> fix: Fix appid assignment error

- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/Options/DispatcherOptions.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/ServiceCollectionExtensions.cs
- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/_Imports.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainEventBusTest.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainServices/CustomDomainService.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainServices/OrderDomainService.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/Infrastructure/CustomLogger.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/_Imports.cs
Event bus, unit of work registration checks changed to warnings
[issues-594](https://github.com/masastack/MASA.Framework/issues/594)
> fix: fix issues-594

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/BindUserRolesModel.cs
- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/UnbindUserRolesModel.cs
- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/Authentication/OpenIdConnect/Masa.Contrib.Authentication.OpenIdConnect.Cache/Models/Mapper.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
> Feature(sdk auth): sdk auth userSerivce add bindRoles method

- src/Contrib/Ddd/Domain/Masa.Contrib.Ddd.Domain/DomainEventBus.cs
- src/Contrib/Ddd/Domain/Tests/Masa.Contrib.Ddd.Domain.Tests/DomainEventBusTest.cs
Event bus and unit of work are optional
issues-594
> fix: fix issues-594, Event bus and unit of work are optional

- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheClientTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache.Tests/MultilevelCacheTest.cs
- src/Contrib/Caching/Masa.Contrib.Caching.MultilevelCache/MultilevelCacheClient.cs
[issues-617](https://github.com/masastack/MASA.Framework/issues/617)
> fix: Fix issues 617

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth.Contracts/Model/UpdateUserBasicInfoModel.cs
add /api/user/basicInfo request Avatar field
> feat:add UpdateUserBasicInfoModel Avatar

- src/BuildingBlocks/StackSdks/Auth/Masa.BuildingBlocks.StackSdks.Auth/Service/IUserService.cs
- src/Contrib/StackSdks/Masa.Contrib.StackSdks.Auth/Service/UserService.cs
- src/Contrib/StackSdks/Tests/Masa.Contrib.StackSdks.Auth.Tests/UserServiceTest.cs
1.Add StackSdks.Auth.Service Remove ThridPartyIdentity Method
> feat:add StackSdks.Auth.Service RemoveThridPartyIdentity

- Directory.Build.props
- src/Contrib/Data/Orm/EFCore/Masa.Contrib.Data.EFCore.Oracle/Masa.Contrib.Data.EFCore.Oracle.csproj
> feat: Supports`.net8.0`

- src/Contrib/Dispatcher/IntegrationEvents/Masa.Contrib.Dispatcher.IntegrationEvents.Dapr/Publisher.cs
> fix:publisher constructor assignment

- src/Contrib/Service/Masa.Contrib.Service.MinimalAPIs/ServiceBase.cs
MapMethods 可以重写以后可以基于ServiceBase继承它然后重写MapMethods 就可以支持过滤器实现等其他操作
> MapMethods 虚拟化，以便重写构建管道实现
